---
# file: roles/deploy/tasks/main.yml
- debug: msg="{{ env }}"

- name: write deploy started
  local_action: shell echo "2" > {{abs_dir}}/{{project}}/{{env}}_flag

- name: deploy new version
  copy: src={{item}} dest=/opt/tomcat7/webapps/{{project}}.war
  with_fileglob: /{abs_dir}}/build/{{project}}/{{latestbuild.stdout}}/*.war
  register: deployresult
  ignore_errors: yes

- debug: msg="{{ deployresult }}"

- name: write deploy failed
  local_action: shell echo "1" > {{abs_dir}}/{{project}}/{{env}}_flag
  when: deployresult.msg != 'All items completed'

- name: write deploy ok
  local_action: shell echo "0" > {{abs_dir}}/{{project}}/{{env}}_flag
  when: deployresult.msg == 'All items completed'
